services:
  postgres:
    image: postgres
    ports:
      - 5432:5432/tcp
    init: true
    restart: "no"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql__data:/var/lib/postgresql/data:rw
  mail:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgresql__data:
